version: "3"
services:
  app:
    build: .
    environment:
      PORT: 7777
      NODE_ENV: development
    ports:
      - 7777:7777
    command: npm run start
    volumes:
      - ./:/app/
      - /app/node_modules
